<?php

return [
    'user' => [
        'dashboard',
        'my_finances',
        'my_purchase',
        'digital_distribution_signup',
        'publishing_signup',
        'account_setting',
    ],
    'basic' => [
        'dashboard',
        'ai_services',
        'ai_mastering',
        'ai_recognition',
//        'ai_mastering_pay',
//        'ai_recognition_pay',
        'my_contents',
        'tracks',
        'my_finances',
        'my_purchase',
        'payment_account',
        'wallet',
        'withdraw',
        'my_sales',
        'track_and_sound_kits_sale',
        'digital_distribution_signup',
        'publishing_signup',
        'account_setting',
    ],
    'seller' => [
        'dashboard',
        'ai_services',
        'ai_mastering',
        'ai_recognition',
//        'ai_mastering_pay',
//        'ai_recognition_pay',
        'my_contents',
        'tracks',
        'sound_kits',
        'my_finances',
        'my_purchase',
        'payment_account',
        'wallet',
        'withdraw',
        'my_sales',
        'track_and_sound_kits_sale',
        'digital_distribution_signup',
        'publishing_signup',
        'promote',
        'promote_track_or_sound_kits',
        'account_setting',
    ],
    'distribution' => [
        'dashboard',
        'ai_services',
        'ai_mastering',
        'ai_recognition',
        'my_contents',
        'single',
        'album',
        'my_finances',
        'my_purchase',
        'payment_account',
        'wallet',
        'withdraw',
        'my_sales',
        'single_and_album_sale',
        'digital_distribution',
        'publishing_signup',
        'promote',
        'promote_single_or_album',
        'account_setting'
    ],
    'publishing' => [
        'dashboard',
        'ai_services',
        'ai_mastering',
        'ai_recognition',
        'my_contents',
        'single',
        'album',
        'my_finances',
        'my_purchase',
        'payment_account',
        'wallet',
        'withdraw',
        'my_sales',
        'single_and_album_sale',
        'digital_distribution_signup',
        'publishing',
        'promote',
        'promote_single_or_album',
        'account_setting',
    ],
];
